### ISSUE TITLE
Safari on Mac

### ISSUE THREAD

**Issue by SteveX** [vimeo/aframe-vimeo-component#6]
Viewing the demo using Safari on a current Mac the video plays but isn't visible. I can hear the audio but the video screen in the scene remains black. Safari 11.0.3 macOS 10.12.6

Works fine on Firefox on macOS 10.12.6.

Also, personally speaking, it would be great to see this working without React as a requirement. Any chance of a demo using a plain old a-frame component?

**Comment by caseypugh** [comment]
Thanks for pointing this out, I also see the same issue. Apparently there is a CORS issues with Safari specifically. Supposedly it has been recently fixed in Safari 11.1, but I have yet to test it out (will try soon) https://github.com/mrdoob/three.js/issues/8110

Regarding your React comment: Unfortunately, there needs to be a server-side component so that you can securely store your private Vimeo token. So yes, this could be built without React, but it'd have to be replaced with another server side framework (Rails, PHP, Sinatra, etc)

**Comment by SteveX** [comment]
PHP would work for me. Without any understanding of React (I have zero understanding of React) it's difficult to extract the a-frame required code from the demo.

I'd love to pursue this though, if you can ever find the time to make your inspiring demo a little more broadly applicable I would jump into this.

**Comment by caseypugh** [comment]
If you're familiar with PHP, then you could pretty easily rebuild this using Vimeo's PHP library https://github.com/vimeo/vimeo.php

You essentially just have to remake the `server.js` class in PHP: https://github.com/vimeo/vimeo-webvr-demo/blob/master/server.js#L16 - all it does is fetch your Vimeo videos for you.

**Comment by SteveX** [comment]
Ok thanks for the pointer, I will look into that. Much appreciated!

**Comment by juniorxsound** [comment]
This was fixed in #10 and tested with Safari Version 12.0.3 on macOS 10.13.6. Feel free to re-open the issue or open a new one if you are still seeing this behavior.
